/*
 * Broker data for the homepage scripts. GENERATED by scripts/build_site.py from
 * content/brokers.json and content/affiliate-links.json; edit those files, not this one.
 * Figures are approximate sample data until content/site.json says dataVerified: true.
 */
window.BROKERS = [
  {
    "id": "ic-markets",
    "domain": "icmarkets.com",
    "name": "IC Markets",
    "color": "#1b75bb",
    "founded": 2007,
    "hq": "Sydney, Australia",
    "regulators": [
      "ASIC",
      "CySEC",
      "FSA (SC)"
    ],
    "minDeposit": 0,
    "account": "Raw Spread",
    "spread": 0.1,
    "commission": 5.28,
    "leverage": 5000,
    "platforms": [
      "MT4",
      "MT5",
      "cTrader",
      "TradingView"
    ],
    "instruments": 2250,
    "bestFor": "Low-cost ECN trading",
    "ratings": {
      "fees": 4.9,
      "platforms": 4.7,
      "trust": 4.3,
      "support": 4.4,
      "education": 3.8
    },
    "pros": [
      "Very tight raw spreads on major pairs",
      "Choice of MT4, MT5, cTrader and TradingView",
      "Fast execution suited to scalping and EAs"
    ],
    "cons": [
      "No FCA-authorised company for UK clients",
      "Very high offshore leverage (up to 1:5000)",
      "Limited proprietary research"
    ],
    "summary": "IC Markets is a popular choice for active and algorithmic traders thanks to raw pricing, deep liquidity and a strong line-up of third-party platforms.",
    "ukStatus": "not-fca",
    "spreadType": "average",
    "verified": true,
    "approx": [
      "commission"
    ],
    "sources": [
      "https://www.icmarkets.com/global/en/trading-accounts/overview",
      "https://www.icmarkets.com/global/en/trading-accounts/raw-spread-account"
    ],
    "checked": "2026-09-30",
    "dataNotes": "Raw Spread: average EUR/USD 0.1 pips, $3.50 per lot per side, min deposit $0 (overview page 30 Sep 2026). Global entity regulated by FSA Seychelles; no FCA entity.",
    "logoExt": "png"
  },
  {
    "id": "pepperstone",
    "domain": "pepperstone.com",
    "name": "Pepperstone",
    "color": "#0f2a4a",
    "founded": 2010,
    "hq": "Melbourne, Australia",
    "regulators": [
      "ASIC",
      "FCA",
      "CySEC",
      "BaFin",
      "DFSA",
      "CMA",
      "SCB"
    ],
    "minDeposit": 0,
    "account": "Razor",
    "spread": 0.1,
    "commission": 4.5,
    "leverage": 30,
    "platforms": [
      "Pepperstone Platform",
      "MT4",
      "MT5",
      "cTrader",
      "TradingView"
    ],
    "instruments": 1444,
    "bestFor": "Active traders wanting top-tier regulation",
    "ratings": {
      "fees": 4.8,
      "platforms": 4.8,
      "trust": 4.8,
      "support": 4.6,
      "education": 4.2
    },
    "pros": [
      "Razor account: raw spreads plus low fixed commission",
      "Five platforms including TradingView and cTrader",
      "No account or inactivity fees"
    ],
    "cons": [
      "No share dealing, ISA or SIPP",
      "£15 fee on international bank-wire withdrawals",
      "Less beginner education than IG or CMC"
    ],
    "summary": "Pepperstone combines low trading costs with some of the broadest regulatory coverage in the industry, making it a well-rounded choice for most forex traders.",
    "ukStatus": "fca",
    "fcaFrn": "684312",
    "lossPct": 72.9,
    "spreadType": "average",
    "verified": true,
    "sources": [
      "https://www.pepperstone.com/en-gb/trading/trading-accounts/",
      "https://pepperstone.com/en-gb/markets/forex/pairs-and-spreads",
      "https://pepperstone.com/en-gb/help-and-support/opening-an-account/whats-the-minimum-deposit-for-a-live-account/"
    ],
    "checked": "2026-09-30",
    "dataNotes": "No minimum deposit for bank transfer (card minimum £10). Razor EUR/USD avg 0.1; commission £2.25/side.",
    "logoExt": "png"
  },
  {
    "id": "oanda",
    "domain": "oanda.com",
    "name": "OANDA",
    "color": "#1a1a1a",
    "founded": 1996,
    "hq": "New York, USA",
    "regulators": [
      "CFTC/NFA",
      "FCA",
      "ASIC",
      "CIRO",
      "MAS"
    ],
    "minDeposit": 0,
    "account": "Standard (spread only)",
    "spread": 0.6,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "OANDA Trade",
      "MT4",
      "MT5",
      "TradingView"
    ],
    "instruments": 120,
    "bestFor": "US traders and beginners",
    "ratings": {
      "fees": 4,
      "platforms": 4.4,
      "trust": 4.9,
      "support": 4.3,
      "education": 4.4
    },
    "pros": [
      "No minimum deposit or withdrawal fees",
      "Spread betting and CFDs on MT4, MT5 and TradingView",
      "Long track record and strong regulation"
    ],
    "cons": [
      "Inactivity fee after 12 months",
      "Standard spreads higher than ECN brokers",
      "Smaller range of non-FX markets"
    ],
    "summary": "OANDA is one of the most established forex brokers, trusted for transparent pricing and available to US residents, with solid tools for newer traders.",
    "ukStatus": "fca",
    "fcaFrn": "542574",
    "lossPct": 76.6,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.oanda.com/uk-en/trading/our-pricing/",
      "https://www.oanda.com/uk-en/trading/spreads-margin/",
      "https://help.oanda.com/uk/en/faqs/minimum-deposit-requirement.htm"
    ],
    "checked": "2026-09-30",
    "dataNotes": "No minimum deposit. EUR/USD from 0.6 pips; core pricing option: 0.0 spread + USD 0.70 per 10k units per side.",
    "logoExt": "png"
  },
  {
    "id": "forex-com",
    "domain": "forex.com",
    "name": "FOREX.com",
    "color": "#00a651",
    "founded": 2001,
    "hq": "New Jersey, USA",
    "regulators": [
      "CFTC/NFA",
      "FCA",
      "ASIC",
      "CIRO",
      "CIMA"
    ],
    "minDeposit": 100,
    "account": "Standard",
    "spread": 0.7,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "FOREX.com Web",
      "MT4",
      "MT5",
      "TradingView"
    ],
    "instruments": 500,
    "bestFor": "Wide choice of currency pairs",
    "ratings": {
      "fees": 4.1,
      "platforms": 4.5,
      "trust": 4.8,
      "support": 4.2,
      "education": 4.3
    },
    "pros": [
      "80+ currency pairs",
      "Part of publicly listed StoneX group",
      "Good in-house research and platform"
    ],
    "cons": [
      "£12 monthly inactivity fee after 12 months",
      "No share dealing or ISA",
      "Fewer non-forex markets than multi-asset brokers"
    ],
    "summary": "FOREX.com offers one of the widest selections of FX pairs, US availability and strong corporate backing, with a capable proprietary platform.",
    "ukStatus": "fca",
    "fcaFrn": "446717",
    "lossPct": 74,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.forex.com/en-uk/trading-accounts/standard-trading-account/",
      "https://www.forex.com/en-uk/help-and-support/faqs/accounts/"
    ],
    "checked": "2026-09-30",
    "dataNotes": "forex.com blocks automated fetches (403); figures from forex.com pages as indexed by search: EUR/USD from 0.7 pts, min initial deposit £100, 74% retail lose. UK entity is StoneX Financial Ltd (FRN 446717); Gain Capital UK (FRN 190864) applied to cancel 23 Sep 2026.",
    "logoExt": "png"
  },
  {
    "id": "ig",
    "domain": "ig.com",
    "name": "IG",
    "color": "#e2001a",
    "founded": 1974,
    "hq": "London, UK",
    "regulators": [
      "FCA",
      "ASIC",
      "BaFin",
      "CFTC/NFA",
      "MAS",
      "FINMA"
    ],
    "minDeposit": 0,
    "account": "CFD / spread bet",
    "spread": 0.6,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "IG Platform",
      "MT4",
      "MT5",
      "ProRealTime",
      "TradingView"
    ],
    "instruments": 15000,
    "bestFor": "Overall best all-rounder",
    "ratings": {
      "fees": 4.3,
      "platforms": 4.8,
      "trust": 5,
      "support": 4.5,
      "education": 4.8
    },
    "pros": [
      "No account, platform or inactivity fees",
      "Decades-long history, parent listed on the LSE",
      "Choice of IG, MT4, MT5, ProRealTime and TradingView"
    ],
    "cons": [
      "Overnight funding on spread bets costs more than on CFDs",
      "Platform can feel overwhelming to beginners",
      "Minimum spreads are not the lowest for high-volume forex traders"
    ],
    "summary": "IG is a global heavyweight offering an enormous range of markets, excellent tools and research, and exceptional regulatory standing.",
    "ukStatus": "fca",
    "fcaFrn": "195355",
    "lossPct": 69,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.ig.com/uk/our-charges",
      "https://www.ig.com/uk/forex/markets-forex",
      "https://www.ig.com/uk/help-and-support/articles/685866-what-s-the-minimum-and-maximum-amount-i-can-deposit"
    ],
    "checked": "2026-09-30",
    "dataNotes": "No minimum by bank transfer; help centre lists £1 card minimum. EUR/USD minimum spread 0.6, no commission on FX. No inactivity fee (charges page, 30 Sep 2026). 15,000+ markets per ig.com/uk.",
    "logoExt": "png"
  },
  {
    "id": "xtb",
    "domain": "xtb.com",
    "name": "XTB",
    "color": "#d71920",
    "founded": 2002,
    "hq": "Warsaw, Poland",
    "regulators": [
      "KNF",
      "FCA",
      "CySEC",
      "FSC (BZ)"
    ],
    "minDeposit": 0,
    "account": "Standard",
    "spread": 0.8,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "xStation 5"
    ],
    "instruments": 11800,
    "bestFor": "Beginners wanting a great app",
    "ratings": {
      "fees": 4.4,
      "platforms": 4.6,
      "trust": 4.5,
      "support": 4.7,
      "education": 4.7
    },
    "pros": [
      "Award-winning xStation platform",
      "Strong education library",
      "Publicly listed on the Warsaw Stock Exchange"
    ],
    "cons": [
      "No MT4, MT5 or TradingView",
      "No spread betting",
      "Inactivity fee after 12 months (not ISAs)"
    ],
    "summary": "XTB is a user-friendly broker built around its excellent xStation platform, with commission-free standard pricing and very good educational content.",
    "ukStatus": "fca",
    "fcaFrn": "522157",
    "lossPct": 74,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.xtb.com/en/account-and-fees",
      "https://www.xtb.com/en/forex"
    ],
    "checked": "2026-09-30",
    "dataNotes": "No minimum deposit; 0% CFD commission; EURUSD minimum spread 0.8 (XTB comparison table dated 13 Jan 2026); 60+ FX pairs.",
    "logoExt": "png"
  },
  {
    "id": "etoro",
    "domain": "etoro.com",
    "name": "eToro",
    "color": "#13c636",
    "founded": 2007,
    "hq": "Tel Aviv, Israel",
    "regulators": [
      "FCA",
      "CySEC",
      "ASIC",
      "FSAS"
    ],
    "minDeposit": 8,
    "account": "eToro CFD",
    "spread": 0.6,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "eToro Platform"
    ],
    "instruments": 5000,
    "bestFor": "Social and copy trading",
    "ratings": {
      "fees": 3.8,
      "platforms": 4.4,
      "trust": 4.4,
      "support": 3.9,
      "education": 4.1
    },
    "pros": [
      "Industry-leading copy trading",
      "Very easy to use, with ISA and GBP account",
      "No inactivity, account or custody fees"
    ],
    "cons": [
      "Spreads quoted as % can be wider for forex",
      "No MetaTrader or spread betting",
      "USD account: US$5 withdrawals and conversion costs"
    ],
    "summary": "eToro is the go-to platform for social and copy trading, trading off slightly higher FX costs for simplicity and community features.",
    "ukStatus": "fca",
    "fcaFrn": "583263",
    "lossPct": 51,
    "spreadType": "typical",
    "verified": true,
    "approx": [
      "minDeposit"
    ],
    "sources": [
      "https://www.etoro.com/trading/fees/cfd-spreads/",
      "https://help.etoro.com/s/article/What-s-the-deposit-minimum?language=en_GB"
    ],
    "checked": "2026-09-30",
    "dataNotes": "EUR/USD spread 0.005% per trade (~0.57 pips at EURUSD 1.1355). UK first deposit US$10.",
    "logoExt": "png"
  },
  {
    "id": "interactive-brokers",
    "domain": "interactivebrokers.com",
    "name": "Interactive Brokers",
    "color": "#d81222",
    "founded": 1978,
    "hq": "Greenwich, USA",
    "regulators": [
      "SEC",
      "CFTC/NFA",
      "FCA",
      "ASIC",
      "CBI",
      "MAS"
    ],
    "minDeposit": 0,
    "account": "IBKR Pro (spot FX)",
    "spread": 0.1,
    "commission": 3.43,
    "leverage": 30,
    "platforms": [
      "Trader Workstation",
      "IBKR Desktop",
      "API"
    ],
    "instruments": 1000000,
    "bestFor": "Professionals and large accounts",
    "ratings": {
      "fees": 4.8,
      "platforms": 4.5,
      "trust": 5,
      "support": 4,
      "education": 4.3
    },
    "pros": [
      "Near-interbank forex pricing with low commission",
      "Access to 170 market centres worldwide",
      "No minimum deposit, inactivity or custody fees"
    ],
    "cons": [
      "Steep learning curve",
      "No spread betting",
      "US$2 minimum commission per forex order"
    ],
    "summary": "Interactive Brokers delivers institutional-grade pricing and market access, best suited to experienced traders comfortable with advanced tools.",
    "ukStatus": "fca",
    "fcaFrn": "208159",
    "lossPct": 57.9,
    "spreadType": "from",
    "verified": true,
    "approx": [
      "commission"
    ],
    "sources": [
      "https://www.interactivebrokers.co.uk/en/pricing/commissions-spot-currencies.php",
      "https://www.interactivebrokers.co.uk/en/pricing/commissions-cfd-forex.php",
      "https://www.interactivebrokers.co.uk/en/trading/products-spot-currencies.php"
    ],
    "checked": "2026-09-30",
    "dataNotes": "Commission 0.2 bps x trade value, min USD 2 per order (Tier I). No account minimum.",
    "logoExt": "png"
  },
  {
    "id": "saxo",
    "domain": "home.saxo",
    "name": "Saxo",
    "color": "#0038a8",
    "founded": 1992,
    "hq": "Copenhagen, Denmark",
    "regulators": [
      "DFSA (DK)",
      "FCA",
      "ASIC",
      "MAS",
      "FINMA"
    ],
    "minDeposit": 0,
    "account": "Classic",
    "spread": 0.7,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "SaxoTraderGO",
      "SaxoTraderPRO",
      "TradingView"
    ],
    "instruments": 71000,
    "bestFor": "Multi-asset investors",
    "ratings": {
      "fees": 4.2,
      "platforms": 4.9,
      "trust": 4.9,
      "support": 4.3,
      "education": 4.4
    },
    "pros": [
      "Superb in-house platforms",
      "Enormous multi-asset product range",
      "Licensed bank in Denmark"
    ],
    "cons": [
      "Best prices need Platinum or VIP tiers",
      "No MetaTrader or spread betting",
      "US$3 commission on forex trades under 50,000 units"
    ],
    "summary": "Saxo is a Danish bank offering premium trading platforms and one of the largest product line-ups available to retail traders.",
    "ukStatus": "fca",
    "fcaFrn": "551422",
    "lossPct": 60,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.home.saxo/en-gb/products/forex",
      "https://www.home.saxo/en-gb/accounts",
      "https://www.home.saxo/en-gb/rates-and-conditions/forex/spreads-and-commissions"
    ],
    "checked": "2026-09-30",
    "dataNotes": "No minimum funding. EURUSD minimum spread 0.7 pips (Classic); fixed USD 3 commission on trades under 50,000 units. 185+ FX pairs.",
    "logoExt": "png"
  },
  {
    "id": "cmc-markets",
    "domain": "cmcmarkets.com",
    "name": "CMC Markets",
    "color": "#0f6e84",
    "founded": 1989,
    "hq": "London, UK",
    "regulators": [
      "FCA",
      "ASIC",
      "CIRO",
      "MAS",
      "BaFin"
    ],
    "minDeposit": 0,
    "account": "CFD / spread bet",
    "spread": 0.6,
    "commission": 0,
    "leverage": 30,
    "platforms": [
      "Next Generation",
      "MT4",
      "TradingView"
    ],
    "instruments": 21000,
    "bestFor": "Charting and technical analysis",
    "ratings": {
      "fees": 4.5,
      "platforms": 4.8,
      "trust": 4.9,
      "support": 4.3,
      "education": 4.4
    },
    "pros": [
      "Advanced charting with pattern recognition",
      "21,000+ instruments including ~300 FX pairs",
      "FTSE 250 group, trading since 1989"
    ],
    "cons": [
      "£10 monthly inactivity fee after a year",
      "Many features can overwhelm new traders",
      "No MT5 or cTrader"
    ],
    "summary": "CMC Markets pairs competitive pricing with a feature-rich Next Generation platform that technical traders will appreciate.",
    "ukStatus": "fca",
    "fcaFrn": "173730",
    "lossPct": 68,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.cmcmarkets.com/en-gb/forex",
      "https://www.cmcmarkets.com/en-gb/compare-trading-accounts",
      "https://www.cmcmarkets.com/en-gb/forex/how-much-do-you-need-to-start-trading-forex"
    ],
    "checked": "2026-09-30",
    "dataNotes": "No minimum deposit. EUR/USD min spread 0.6 (indicative table). FX Active account: 0.0 spread + 0.0025% commission per transaction.",
    "logoExt": "png"
  },
  {
    "id": "exness",
    "domain": "exness.com",
    "name": "Exness",
    "color": "#f5c400",
    "founded": 2008,
    "hq": "Limassol, Cyprus",
    "regulators": [
      "CySEC",
      "FSCA",
      "FSA (SC)"
    ],
    "minDeposit": 8,
    "account": "Standard",
    "spread": 0.3,
    "commission": 0.0,
    "leverage": 2000,
    "platforms": [
      "MT4",
      "MT5",
      "Exness Terminal"
    ],
    "instruments": 250,
    "bestFor": "Small accounts and instant withdrawals",
    "ratings": {
      "fees": 4.4,
      "platforms": 4.3,
      "trust": 4,
      "support": 4.5,
      "education": 3.6
    },
    "pros": [
      "Very low minimum deposit (about £8 / US$10)",
      "Fast, often instant withdrawals",
      "Wide range of account types"
    ],
    "cons": [
      "Very high leverage only via offshore entities",
      "Limited research and education",
      "Smaller product range"
    ],
    "summary": "Exness appeals to traders starting small, with a low minimum deposit, flexible accounts and a reputation for fast withdrawals.",
    "ukStatus": "not-available",
    "spreadType": "average",
    "verified": true,
    "approx": [
      "minDeposit"
    ],
    "sources": [
      "https://www.exness.com/standard-accounts/",
      "https://www.exness.com/regulation/"
    ],
    "checked": "2026-09-29",
    "dataNotes": "Does not serve UK residents. Standard: avg EURUSD 0.3 pips, commission-free, min deposit ~US$10 (from exness.com pages via search).",
    "logoExt": "png"
  },
  {
    "id": "avatrade",
    "domain": "avatrade.com",
    "name": "AvaTrade",
    "color": "#2a3b8f",
    "founded": 2006,
    "hq": "Dublin, Ireland",
    "regulators": [
      "CBI",
      "ASIC",
      "FSCA",
      "FSA (JP)",
      "ADGM"
    ],
    "minDeposit": 100,
    "account": "Standard",
    "spread": 0.9,
    "commission": 0.0,
    "leverage": 400,
    "platforms": [
      "MT4",
      "MT5",
      "AvaTradeGO",
      "WebTrader"
    ],
    "instruments": 1250,
    "bestFor": "Fixed spreads and risk management",
    "ratings": {
      "fees": 4.1,
      "platforms": 4.3,
      "trust": 4.5,
      "support": 4.2,
      "education": 4.4
    },
    "pros": [
      "Fixed spreads offer cost certainty",
      "AvaProtect trade insurance feature",
      "Regulated across several continents"
    ],
    "cons": [
      "Not available to UK residents",
      "Inactivity fee after 3 months, admin fee after 12",
      "No raw-spread account"
    ],
    "summary": "AvaTrade offers predictable fixed spreads and useful risk-management features, backed by regulation across multiple jurisdictions.",
    "ukStatus": "not-available",
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.avatrade.com/trading-info/financial-instruments-index/forex",
      "https://support.avatrade.com/hc/en-us/articles/360017588538-Does-AvaTrade-accept-traders-worldwide"
    ],
    "checked": "2026-09-30",
    "dataNotes": "Does not accept UK residents. EUR/USD from 0.9 pips; min deposit 100 in account currency.",
    "logoExt": "png"
  },
  {
    "id": "ironfx",
    "domain": "ironfx.com",
    "name": "IronFX",
    "color": "#0d3b78",
    "founded": 2010,
    "hq": "Limassol, Cyprus",
    "regulators": [
      "FSC (BVI)",
      "CySEC",
      "FSCA"
    ],
    "minDeposit": 38,
    "account": "Standard (floating)",
    "spread": 1.2,
    "commission": 0.0,
    "leverage": 1000,
    "platforms": [
      "MT4",
      "MT5",
      "WebTrader"
    ],
    "instruments": 300,
    "bestFor": "Bonuses and account variety",
    "ratings": {
      "fees": 4,
      "platforms": 4,
      "trust": 3.9,
      "support": 4.1,
      "education": 4
    },
    "pros": [
      "Choice of fixed, floating and zero-spread accounts",
      "Low suggested starting deposit",
      "MT4 and MT5 available"
    ],
    "cons": [
      "Website not directed at UK residents",
      "Mixed reputation from past client complaints",
      "High leverage only through offshore entities"
    ],
    "summary": "IronFX offers a broad menu of account types and MetaTrader platforms under several regulators, but its standard pricing is not the cheapest and its reputation is mixed.",
    "ukStatus": "not-available",
    "spreadType": "unverified",
    "verified": false,
    "approx": [
      "minDeposit",
      "commission"
    ],
    "sources": [
      "https://www.ironfx.com/en/faq-page/"
    ],
    "checked": "2026-09-30",
    "dataNotes": "IronFX states its site is not directed at UK residents. ironfx.com could not be read from this environment (connection refused at proxy); spread/deposit figures not verified.",
    "logoExt": "png"
  },
  {
    "id": "pu-prime",
    "domain": "puprime.com",
    "name": "PU Prime",
    "color": "#0b2447",
    "founded": 2015,
    "hq": "Victoria, Seychelles",
    "regulators": [
      "ASIC",
      "FSCA",
      "FSC (MU)",
      "FSA (SC)"
    ],
    "minDeposit": 38,
    "account": "Standard",
    "spread": 1.3,
    "commission": 0.0,
    "leverage": 1000,
    "platforms": [
      "MT4",
      "MT5",
      "PU Prime App",
      "WebTrader"
    ],
    "instruments": 1000,
    "bestFor": "High leverage and copy trading",
    "ratings": {
      "fees": 4,
      "platforms": 4.2,
      "trust": 3.6,
      "support": 4.3,
      "education": 3.8
    },
    "pros": [
      "Low minimum deposit (about £38 / US$50) on Standard",
      "Copy trading and a capable mobile app",
      "Up to 1:1000 leverage offshore"
    ],
    "cons": [
      "Most international clients onboarded via Seychelles entity",
      "FCA has issued a warning about the Seychelles entity",
      "Prime and ECN accounts need large deposits"
    ],
    "summary": "PU Prime (formerly Pacific Union) targets active traders with high leverage and copy trading, though most clients are served by its lightly regulated offshore entity.",
    "ukStatus": "not-fca",
    "spreadType": "from",
    "verified": true,
    "approx": [
      "minDeposit"
    ],
    "sources": [
      "https://www.puprime.com/account-types/",
      "https://helpcenter.puprime.com/hc/en-001/articles/360004364635-What-is-the-difference-between-Standard-and-Prime-account"
    ],
    "checked": "2026-09-29",
    "dataNotes": "Standard: min deposit $50, no commission, spreads from 1.3; Prime: $1,000 min, $3.5/side. Regulated offshore (FSC Mauritius, SVG FSA); no FCA entity.",
    "logoExt": "png"
  },
  {
    "id": "xm",
    "domain": "xm.com",
    "name": "XM",
    "color": "#d51820",
    "founded": 2009,
    "hq": "Limassol, Cyprus",
    "regulators": [
      "CySEC",
      "ASIC",
      "DFSA",
      "FSC (BZ)"
    ],
    "minDeposit": 4,
    "account": "Standard",
    "spread": 1.6,
    "commission": 0.0,
    "leverage": 1000,
    "platforms": [
      "MT4",
      "MT5",
      "XM App"
    ],
    "instruments": 1400,
    "bestFor": "Very small starting deposits",
    "ratings": {
      "fees": 3.9,
      "platforms": 4.3,
      "trust": 4.2,
      "support": 4.5,
      "education": 4.6
    },
    "pros": [
      "Tiny minimum deposit (about £4 / US$5)",
      "Strong free education and webinars",
      "Multilingual 24/5 support"
    ],
    "cons": [
      "UK retail onboarding unclear; global entity is offshore",
      "Zero (raw-spread) account discontinued",
      "Standard account spreads are wide"
    ],
    "summary": "XM is a beginner-friendly broker with a tiny minimum deposit and excellent educational content, offset by relatively wide spreads on its standard account.",
    "ukStatus": "not-fca",
    "spreadType": "unverified",
    "verified": false,
    "approx": [
      "minDeposit"
    ],
    "sources": [
      "https://www.xm.com/account-types"
    ],
    "checked": "2026-09-30",
    "dataNotes": "xm.com blocks automated reads. Group has FCA entity Trading Point of Financial Instruments UK Ltd (FRN 705428) but third-party reviews report XM no longer accepts UK clients; could not confirm (30 Sep 2026). Global: XM Global Ltd, FSC Belize 8557558. Zero account ceased.",
    "logoExt": "png"
  },
  {
    "id": "vantage",
    "domain": "vantagemarkets.com",
    "name": "Vantage",
    "color": "#0b1a33",
    "founded": 2009,
    "hq": "Sydney, Australia",
    "regulators": [
      "ASIC",
      "FCA",
      "CIMA",
      "VFSC"
    ],
    "minDeposit": 50,
    "account": "RAW ECN",
    "spread": 0.1,
    "commission": 2,
    "leverage": 30,
    "platforms": [
      "MT4",
      "MT5",
      "TradingView",
      "ProTrader"
    ],
    "instruments": 1000,
    "bestFor": "Low-cost raw pricing",
    "ratings": {
      "fees": 4.6,
      "platforms": 4.5,
      "trust": 4.1,
      "support": 4.3,
      "education": 4
    },
    "pros": [
      "£1 per side RAW ECN commission on GBP accounts",
      "Lloyd's excess-of-FSCS insurance up to £1m",
      "Spread betting plus MT4, MT5 and TradingView"
    ],
    "cons": [
      "Limited research output",
      "No share dealing or ISA",
      "Premium pricing needs a £25,000 deposit"
    ],
    "summary": "Vantage combines tight raw pricing and modern platform choices with a low entry point, making it a solid option for cost-conscious traders.",
    "ukStatus": "fca",
    "fcaFrn": "590299",
    "lossPct": 70.98,
    "spreadType": "from",
    "verified": true,
    "sources": [
      "https://www.vantagemarkets.co.uk/trading/fees/commission/",
      "https://helpcenter.vantagemarkets.co.uk/hc/en-gb/articles/11933274655247-What-is-a-RAW-ECN-account"
    ],
    "checked": "2026-09-30",
    "dataNotes": "RAW ECN GBP account: £1 per lot per side (£2 round turn) from UK commission page. Min deposit 50 units of account currency and EURUSD min 0.1 pip from Vantage help centre (page blocks automated reads).",
    "logoExt": "png"
  },
  {
    "id": "fp-markets",
    "domain": "fpmarkets.com",
    "name": "FP Markets",
    "color": "#1a2f5a",
    "founded": 2005,
    "hq": "Sydney, Australia",
    "regulators": [
      "ASIC",
      "CySEC",
      "FSCA",
      "FSA (SC)"
    ],
    "minDeposit": 75,
    "account": "Raw",
    "spread": 0.0,
    "commission": 4.53,
    "leverage": 500,
    "platforms": [
      "MT4",
      "MT5",
      "cTrader",
      "TradingView"
    ],
    "instruments": 10000,
    "bestFor": "Raw spreads on every major platform",
    "ratings": {
      "fees": 4.7,
      "platforms": 4.6,
      "trust": 4.4,
      "support": 4.5,
      "education": 4.1
    },
    "pros": [
      "Very low raw-account costs",
      "MT4, MT5, cTrader and TradingView",
      "Large range including share CFDs"
    ],
    "cons": [
      "No FCA-authorised company for UK clients",
      "No proprietary platform",
      "Higher leverage only via offshore entity"
    ],
    "summary": "FP Markets is a long-running Australian broker offering some of the lowest raw trading costs across all the popular third-party platforms.",
    "ukStatus": "not-fca",
    "spreadType": "from",
    "verified": true,
    "approx": [
      "minDeposit",
      "commission"
    ],
    "sources": [
      "https://www.fpmarkets.com/account-types/forex-account-types/",
      "https://www.fpmarkets.com/mt4-5-fees-charges/"
    ],
    "checked": "2026-09-30",
    "dataNotes": "From fpmarkets.com pages as indexed by search (site blocks automated reads): Raw from 0.0 pips, US$3 per lot per side, min deposit ~US$100. Regulated by ASIC/CySEC; no FCA entity found.",
    "logoExt": "png"
  },
  {
    "id": "tickmill",
    "domain": "tickmill.com",
    "name": "Tickmill",
    "color": "#0e2a47",
    "founded": 2014,
    "hq": "London, UK",
    "regulators": [
      "FCA",
      "CySEC",
      "FSCA",
      "DFSA",
      "FSA (SC)"
    ],
    "minDeposit": 75,
    "account": "Raw",
    "spread": 0.2,
    "commission": 4.53,
    "leverage": 30,
    "platforms": [
      "MT4",
      "MT5",
      "TradingView"
    ],
    "instruments": 600,
    "bestFor": "Scalpers and algo traders",
    "ratings": {
      "fees": 4.8,
      "platforms": 4.3,
      "trust": 4.4,
      "support": 4.2,
      "education": 4
    },
    "pros": [
      "Low raw-account commission ($3 per lot per side)",
      "FCA and CySEC regulated",
      "Fast execution, EA-friendly"
    ],
    "cons": [
      "No spread betting or ISA",
      "No proprietary trading platform for CFDs",
      "Classic account spreads from 1.6 pips"
    ],
    "summary": "Tickmill is built for cost-sensitive active traders, with low raw-account commissions and fast execution under solid regulation.",
    "ukStatus": "fca",
    "fcaFrn": "717270",
    "lossPct": 69,
    "spreadType": "example",
    "verified": true,
    "approx": [
      "minDeposit",
      "commission"
    ],
    "sources": [
      "https://www.tickmill.com/uk/conditions/trading-costs-fees",
      "https://www.tickmill.com/uk/about/faq/what-is-the-minimum-deposit"
    ],
    "checked": "2026-09-30",
    "dataNotes": "Raw: from 0.0 pips, $3 per lot per side; EURUSD 0.2 pips used in Tickmill's own worked example. Starting deposit $100 (varies by base currency).",
    "logoExt": "png"
  },
  {
    "id": "hfm",
    "domain": "hfm.com",
    "name": "HFM",
    "color": "#d0121b",
    "founded": 2010,
    "hq": "Limassol, Cyprus",
    "regulators": [
      "CySEC",
      "FCA",
      "FSCA",
      "DFSA",
      "FSA (SC)",
      "CMA"
    ],
    "minDeposit": 19,
    "account": "Zero",
    "spread": 0.0,
    "commission": 4.53,
    "leverage": 30,
    "platforms": [
      "MT4",
      "MT5",
      "HFM App"
    ],
    "instruments": 1000,
    "bestFor": "Account flexibility and promotions",
    "ratings": {
      "fees": 4,
      "platforms": 4.3,
      "trust": 4.2,
      "support": 4.4,
      "education": 4.3
    },
    "pros": [
      "No minimum deposit on Premium account",
      "Wide range of account types",
      "Good education and market analysis"
    ],
    "cons": [
      "High leverage advertised internationally is not available to UK retail clients",
      "No spread betting, TradingView or ISA",
      "Premium account spreads are wide"
    ],
    "summary": "HFM (formerly HotForex) offers lots of account options and trading tools across many jurisdictions, though its standard pricing is on the high side.",
    "ukStatus": "fca",
    "fcaFrn": "801701",
    "lossPct": 71.46,
    "spreadType": "from",
    "verified": true,
    "approx": [
      "minDeposit",
      "commission"
    ],
    "sources": [
      "https://hfmarkets.co.uk/uk/en/account-types/zero-spread-account.html",
      "https://www.hfmarkets.co.uk/en/help/faqs"
    ],
    "checked": "2026-09-30",
    "dataNotes": "From hfmarkets.co.uk pages as indexed by search (site blocks automated reads): Zero account min deposit $25, commission from $3 per lot (per side assumed), 71.46% of retail lose money.",
    "logoExt": "png"
  },
  {
    "id": "fxtm",
    "domain": "forextime.com",
    "name": "FXTM",
    "color": "#c4d600",
    "founded": 2011,
    "hq": "Limassol, Cyprus",
    "regulators": [
      "FSC (MU)",
      "FSCA",
      "CMA"
    ],
    "minDeposit": 500,
    "account": "Advantage",
    "spread": 0.0,
    "commission": 5.28,
    "leverage": 1000,
    "platforms": [
      "MT4",
      "MT5",
      "FXTM Trader"
    ],
    "instruments": 1000,
    "bestFor": "Emerging-market traders",
    "ratings": {
      "fees": 4.3,
      "platforms": 4.2,
      "trust": 4.1,
      "support": 4.2,
      "education": 4.4
    },
    "pros": [
      "Advantage account offers raw spreads",
      "Strong presence in Africa and Asia",
      "Good educational resources"
    ],
    "cons": [
      "Not available to UK residents",
      "Advantage account needs a 500 minimum deposit",
      "Very high offshore leverage adds risk"
    ],
    "summary": "FXTM (ForexTime) has a strong following in emerging markets, pairing raw-spread accounts with helpful education and local support.",
    "ukStatus": "not-available",
    "spreadType": "from",
    "verified": true,
    "approx": [
      "commission"
    ],
    "sources": [
      "https://www.fxtm.com/en/trading/accounts/"
    ],
    "checked": "2026-09-30",
    "dataNotes": "forextime.com/uk now redirects to fxtm.com/en; Exinity Limited (FSC Mauritius) states it does not provide services to UK residents (checked 30 Sep 2026). Advantage: spreads from 0, $3.5 per lot per side, min deposit 500 USD/EUR/GBP.",
    "logoExt": ""
  },
  {
    "id": "axi",
    "domain": "axi.com",
    "name": "Axi",
    "color": "#e3002b",
    "founded": 2007,
    "hq": "Sydney, Australia",
    "regulators": [
      "ASIC",
      "FCA",
      "DFSA",
      "FMA"
    ],
    "minDeposit": 0,
    "account": "Pro",
    "spread": 0.0,
    "commission": 3.4,
    "leverage": 30,
    "platforms": [
      "Axi Platform",
      "MT4",
      "MT5",
      "Axi Copy"
    ],
    "instruments": 140,
    "bestFor": "MT4 traders wanting strong regulation",
    "ratings": {
      "fees": 4.5,
      "platforms": 4,
      "trust": 4.6,
      "support": 4.4,
      "education": 4.1
    },
    "pros": [
      "No required minimum deposit; free card, PayPal and bank deposits",
      "Raw-spread Pro account",
      "24/7 support by live chat and WhatsApp"
    ],
    "cons": [
      "No TradingView",
      "Limited in-house research",
      "No share dealing or ISA"
    ],
    "summary": "Axi is a well-regulated, no-frills MetaTrader 4 broker with competitive raw pricing and no minimum deposit.",
    "ukStatus": "fca",
    "fcaFrn": "509746",
    "lossPct": 66.36,
    "spreadType": "from",
    "verified": true,
    "approx": [
      "commission"
    ],
    "sources": [
      "https://www.axi.com/uk/trading-accounts",
      "https://www.axi.com/uk/faqs/deposit-and-withdrawal/what-is-the-minimum-i-can-deposit"
    ],
    "checked": "2026-09-30",
    "dataNotes": "Pro: EURUSD from 0 pips, commission $4.5 round trip (charged in account currency equivalent); Standard: from 0.68 pips, no commission. No minimum deposit (recommended $100).",
    "logoExt": "png"
  }
];

window.TIER1_REGULATORS = ["FCA", "ASIC", "CFTC/NFA", "SEC", "BaFin", "FINMA", "MAS", "CIRO", "CBI", "DFSA (DK)", "FSA (JP)"];

window.RATING_CATEGORIES = [
  {
    "key": "fees",
    "label": "Fees & costs",
    "weight": 0.3,
    "desc": "Spreads, commissions, swaps and non-trading fees such as inactivity and withdrawal charges."
  },
  {
    "key": "trust",
    "label": "Trust & regulation",
    "weight": 0.25,
    "desc": "Number and quality of licences, track record, listed status and client-fund protections."
  },
  {
    "key": "platforms",
    "label": "Platforms & tools",
    "weight": 0.2,
    "desc": "Platform choice, charting, execution quality, mobile apps and automated trading support."
  },
  {
    "key": "education",
    "label": "Research & education",
    "weight": 0.15,
    "desc": "Market analysis, tutorials, webinars and tools that help traders improve."
  },
  {
    "key": "support",
    "label": "Customer support",
    "weight": 0.1,
    "desc": "Availability, speed and quality of help via live chat, phone and email."
  }
];

window.AFFILIATE_LINKS = {};

window.SITE_FX = {"date": "2026-09-29", "source": "European Central Bank reference rates", "EURUSD": 1.1355, "EURGBP": 0.85718, "GBPUSD": 1.3247, "pipValueGBP": 7.5489};

// Top picks only rank FCA-authorised brokers when true (content/site.json guidesFcaOnly).
window.SITE_FCA_ONLY = true;
